-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: check-json
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: pretty-format-json
        args: ['--indent', '2', '--autofix', '--no-sort-keys']
